import { Button, VerticalBox, HorizontalBox, ListView, Palette, SpinBox } from "std-widgets.slint";
import { Book } from "book-management.slint";

export struct supplier {
    id: int,
    name : string,
    telephone: string,
    email: string,
    address: string,
    fax: string,
    books: [Book],
}

component supplierItem inherits Rectangle {
    in property <supplier> supplier;
    in property <bool> has-login;
    in property <length> item-width;

    callback clicked <=> touch.clicked;

    states [
        pressed when touch.pressed: {
            state.opacity: 0.6;
        }
        hover when touch.has-hover: {
            state.opacity: 0.4;
        }
    ]

    VerticalLayout {
        alignment: LayoutAlignment.start;
        Rectangle {
            touch := TouchArea {
                width: 100%;
                height: 100%;
            }
            HorizontalLayout {
                alignment: LayoutAlignment.start;
                Rectangle {
                    width: root.item-width;
                    state := Rectangle {
                        opacity: 0;
                        background: Colors.gray;

                        animate opacity { duration: 150ms; }
                    }

                    VerticalBox {
                        alignment: LayoutAlignment.start;
                        Text {
                            text: "Supplier id: " + root.supplier.id;
                        }

                        Text {
                            text: "Supplier name: " + root.supplier.name;
                        }

                        Text {
                            text: "Supplier telephone: " + root.supplier.telephone;
                        }

                        Text {
                            text: "Supplier email: " + root.supplier.email;
                        }

                        Text {
                            text: "Supplier address: " + root.supplier.address;
                        }

                        Text {
                            text: "Supplier fax: " + root.supplier.fax;
                        }
                    }
                }
            }
        }
    }    
}


export component supplierView inherits Window {
    in property <bool> has-login;
    in property <[supplier]> suppliers;
    in property <length> item-width: 300px;
    in property <length> window-width: 800px;
    in property <length> window-height: 600px;

    out property <int> selected-supplier-id: -1;
    
    callback open-supplier-detail(int);

    VerticalBox {
        alignment: LayoutAlignment.start;
        ListView {
            preferred-height: root.window-height;
            for supplier[index] in suppliers: supplierItem {
                supplier: suppliers[index];
                has-login: root.has-login;
                item-width: root.item-width;

                clicked => {
                    root.open-supplier-detail(supplier.id);
                }
            }
        }
    }
}
