import { VerticalBox, HorizontalBox } from "std-widgets.slint";

export struct BookDetail {
        id: int,
        isbn: string,
        title: string,
        authors: [string],
        publisher: string,
        suppliers: [string],
        series: [string],
        price: string,
        keywords: [string],
        catalog: string,
        cover: image,
}

export component BookDetailView inherits Rectangle {
    in property <BookDetail> book;
    in property <length> image-width: 100px;
    in property <float> image-aspect-ratio: 1;
    in property <length> item-width: 300px;

    width: root.item-width;

    VerticalBox {
        alignment: LayoutAlignment.start;
        Rectangle {
            touch := TouchArea {
                width: 100%;
                height: 100%;
            }

            HorizontalBox {
                alignment: LayoutAlignment.start;
                Image {
                    width: root.image-width;
                    height: root.image-width / root.image-aspect-ratio;
                    source: root.book.cover;
                }

                Rectangle {
                    width: root.item-width - root.image-width;

                    VerticalBox {
                        alignment: LayoutAlignment.start;
                        Text {
                            text: "ISBN: " + root.book.isbn;
                        }

                        Text {
                            text: "Title: " + root.book.title;
                        }

                        HorizontalLayout {
                            alignment: LayoutAlignment.start;
                            Text {
                                text: "Authors: ";
                            }

                            for author[index] in root.book.authors: Text {
                                text: index < root.book.authors.length - 1 ? author + ", " : author;
                            }
                        }

                        Text {
                            text: "Publisher: " + root.book.publisher;
                        }

                        Text {
                            text: "Price: " + root.book.price;
                        }

                        HorizontalLayout {
                            alignment: LayoutAlignment.start;
                            Text {
                                text: "Keywords: ";
                            }

                            for keyword[index] in root.book.keywords: Text {
                                text: index < root.book.keywords.length - 1 ? keyword + ", " : keyword;
                            }
                        }

                        Text {
                            text: "Catalog: " + root.book.catalog;
                        }

                        HorizontalLayout {
                            alignment: LayoutAlignment.start;
                            Text {
                                text: "Suppliers: ";
                            }

                            for supplier[index] in root.book.suppliers: Text {
                                text: index < root.book.suppliers.length - 1 ? supplier + ", " : supplier;
                            }
                        }

                        HorizontalLayout {
                            alignment: LayoutAlignment.start;
                            Text {
                                text: "Series: ";
                            }

                            for series[index] in root.book.series: Text {
                                text: index < root.book.series.length - 1 ? series + ", " : series;
                            }
                        }
                    }
                }
            }
        }
    }
}
