import { Button, VerticalBox, HorizontalBox, ListView, Palette, SpinBox } from "std-widgets.slint";

export struct Book {
    id: int,
    isbn: string,
    title: string,
    authors: [string],
    publisher: string,
    price: string,
    keywords: [string],
    cover: image,
}

component BookListItem inherits Rectangle {
    in property <Book> book;
    in property <bool> has-login;
    in property <length> image-width;
    in property <float> image-aspect-ratio;
    in property <length> item-width;

    callback clicked <=> touch.clicked;
    callback add-to-cart(int, int);

    states [
        pressed when touch.pressed: {
            state.opacity: 0.6;
        }
        hover when touch.has-hover: {
            state.opacity: 0.4;
        }
    ]

    VerticalLayout {
        alignment: LayoutAlignment.start;
        Rectangle {
            touch := TouchArea {
                width: 100%;
                height: 100%;
            }

            HorizontalLayout {
                alignment: LayoutAlignment.start;
                Image {
                    width: root.image-width;
                    height: root.image-width / root.image-aspect-ratio;
                    source: root.book.cover;
                }

                Rectangle {
                    width: root.item-width - root.image-width;
                    state := Rectangle {
                        opacity: 0;
                        background: Colors.gray;

                        animate opacity { duration: 150ms; }
                    }

                    VerticalBox {
                        alignment: LayoutAlignment.start;

                        Text {
                            text: "ISBN: " + root.book.isbn;
                        }

                        Text {
                            text: "Title: " + root.book.title;
                        }

                        HorizontalLayout {
                            alignment: LayoutAlignment.start;
                            Text {
                                text: "Authors: ";
                            }

                            for author[index] in root.book.authors: Text {
                                text: index < root.book.authors.length - 1 ? author + ", " : author;
                                vertical-alignment: TextVerticalAlignment.center;
                            }
                        }

                        Text {
                            text: "Publisher: " + root.book.publisher;
                        }

                        Text {
                            text: "Price: " + root.book.price;
                        }

                        HorizontalLayout {
                            alignment: LayoutAlignment.start;
                            Text {
                                text: "Keywords: ";
                            }

                            for keyword[index] in root.book.keywords: Text {
                                text: index < root.book.keywords.length - 1 ? keyword + ", " : keyword;
                                vertical-alignment: TextVerticalAlignment.center;
                            }
                        }
                    }
                }
            }
        }

        add-widget := HorizontalLayout {
            alignment: LayoutAlignment.end;
            padding-top: 8px;
            visible: root.has-login;
            quantity := SpinBox {
                minimum: 1;
                maximum: 100;
                value: 1;
            }

            add-button := Button {
                text: "Add to Cart";
                clicked => {
                    root.add-to-cart(root.book.id, quantity.value);
                }
            }
        }
    }
}

export component BookListView inherits Window {
    in property <bool> has-login;
    in property <[Book]> books;
    in property <length> image-width: 100px;
    in property <float> image-aspect-ratio: 1.5;
    in property <length> item-width: 300px;

    callback add-to-cart(int, int);

    out property <int> selected-book-id: -1;
    VerticalLayout {
        HorizontalLayout {
            alignment: LayoutAlignment.center;
            VerticalBox {
                for book[index] in books: BookListItem {
                    book: books[index];
                    has-login: root.has-login;
                    image-width: root.image-width;
                    image-aspect-ratio: root.image-aspect-ratio;
                    item-width: root.item-width;

                    clicked => {
                        root.selected-book-id = books[index].id;
                    }

                    add-to-cart(id, quantity) => {
                        root.add-to-cart(id, quantity);
                    }
                }
            }
        }
    }
}
