import { Button, VerticalBox, HorizontalBox, ListView, SpinBox} from "std-widgets.slint"; 
import { SelectorComboBox } from "util-widget.slint";
export struct Book {
    id: int,
    isbn: string,
    title: string,
    authors: [string],
    publisher: string,
    price: string,
    keywords: [string],
    cover: image,
    cover: image,
}

component BookListItem inherits Rectangle {
    in property <Book> book;
    in property <bool> has-login;
    in property <length> image-width;
    in property <float> image-aspect-ratio;
    in property <length> item-width;

    callback clicked <=> touch.clicked;
    callback edit-stock(int, int);

    states [
        pressed when touch.pressed: {
            state.opacity: 0.6;
        }
        hover when touch.has-hover: {
            state.opacity: 0.4;
        }
    ]

    VerticalLayout {
        alignment: LayoutAlignment.start;
        Rectangle {
            touch := TouchArea {
                width: 100%;
                height: 100%;
            }

            HorizontalLayout {
                alignment: LayoutAlignment.start;
                Image {
                    width: root.image-width;
                    height: root.image-width / root.image-aspect-ratio;
                    source: root.book.cover;
                }

                Rectangle {
                    width: root.item-width - root.image-width;
                    state := Rectangle {
                        opacity: 0;
                        background: Colors.gray;

                        animate opacity { duration: 150ms; }
                    }

                    VerticalBox {
                        alignment: LayoutAlignment.start;

                        Text {
                            text: "ISBN: " + root.book.isbn;
                        }

                        Text {
                            text: "Title: " + root.book.title;
                        }

                        HorizontalLayout {
                            alignment: LayoutAlignment.start;
                            Text {
                                text: "Authors: ";
                            }

                            for author[index] in root.book.authors: Text {
                                text: index < root.book.authors.length - 1 ? author + ", " : author;
                                vertical-alignment: TextVerticalAlignment.center;
                            }
                        }

                        Text {
                            text: "Publisher: " + root.book.publisher;
                        }

                        Text {
                            text: "Price: " + root.book.price;
                        }

                        HorizontalLayout {
                            alignment: LayoutAlignment.start;
                            Text {
                                text: "Keywords: ";
                            }

                            for keyword[index] in root.book.keywords: Text {
                                text: index < root.book.keywords.length - 1 ? keyword + ", " : keyword;
                                vertical-alignment: TextVerticalAlignment.center;
                            }
                        }
                    }
                }
            }
        }
    }
}

export component InventoryManagement inherits Window {
    in property <bool> has-login;
    in property <[Book]> books;
    in property <length> image-width: 100px;
    in property <float> image-aspect-ratio: 1.5;
    in property <length> item-width: 300px;
    in property <length> window-width: 800px;
    in property <length> window-height: 600px;

    out property <int> selected-book-id: -1;

    callback open-book-detail(int);
    callback edit-stock(int, int);
    callback add-book();
    //add-book负责弹出添加新书籍的窗口

    VerticalBox {
        alignment: LayoutAlignment.start;
        ListView {
            preferred-height: root.window-height;
            for book in books: BookListItem {
                book: book; // 使用当前书籍
                has-login: root.has-login;
                image-width: root.image-width;
                image-aspect-ratio: root.image-aspect-ratio;
                item-width: root.item-width;

                clicked => {
                    root.open-book-detail(book.id);
                }
                edit-stock(id, quantity) => {
                    root.edit-stock(book.id, quantity); // 处理库存编辑
                }
            }
        }

        HorizontalLayout {
            alignment: LayoutAlignment.end;
            padding-top: 8px;
            padding-bottom: 8px;
            add-book-button := Button {
                text: "Add Book";
                clicked => {
                    root.add-book();
                }
            }
        }
    }
}
