import { VerticalBox, Button, ListView } from "std-widgets.slint";

export struct PurchaseOrder {
    id: int,
    order_date: string,
    expected_delivery_date: string,
    status: string,
    total_price: string,
}

component PurchaseOrderItem inherits Rectangle {
    in property <PurchaseOrder> order;
    in property <length> item-width;

    width: root.item-width;
    callback clicked <=> touch.clicked;

    states [
        pressed when touch.pressed: {
            state.opacity: 0.6;
        }
        hover when touch.has-hover: {
            state.opacity: 0.4;
        }
    ]

    VerticalLayout {
        alignment: LayoutAlignment.start;
        width: root.item-width;
        Rectangle {
            touch := TouchArea {
                width: 100%;
                height: 100%;
            }

            state := Rectangle {
                opacity: 0;
                background: Colors.gray;

                animate opacity { duration: 150ms; }
            }

            VerticalLayout {
                alignment: LayoutAlignment.start;
                VerticalBox {
                    alignment: LayoutAlignment.start;
                    Text {
                        text: "Order ID: " + root.order.id;
                    }

                    Text {
                        text: "Order Date: " + root.order.order_date;
                    }

                    Text {
                        text: "Expected Delivery Date: " + root.order.expected_delivery_date;
                    }

                    Text {
                        text: "Total Price: " + root.order.total_price;
                    }

                    Text {
                        text: "Status: " + root.order.status;
                    }
                }
            }
        }
    }
}

export component PurchaseOrderHistoryView inherits Window {
    in property <[PurchaseOrder]> orders;
    in property <length> item-width;
    in property <length> window-width;
    in property <length> window-height;

    callback open-purchase-order-detail(int);

    VerticalBox {
        alignment: LayoutAlignment.start;
        ListView {
            preferred-height: root.window-height;

            for order[index] in root.orders: PurchaseOrderItem {
                order: order;
                item-width: root.item-width;

                clicked => {
                    open-purchase-order-detail(order.id);
                }
            }
        }
    }
}
