import { HorizontalBox, VerticalBox, Button } from "std-widgets.slint";

export struct UserDetail {
    admin_id: int,
    username: string,
    role: string,
}

export component UserDetailView inherits Window {
    in property <UserDetail> user-detail;
    in property <bool> error-logout;

    callback user-logout();
    callback get-user-detail();
    callback user-register();

    width: 100%;
    height: 100%;

    init => {
        get-user-detail()
    }

    VerticalLayout {
        alignment: LayoutAlignment.center;
        HorizontalBox {
            alignment: LayoutAlignment.center;
            VerticalBox {
                Text {
                    text: "Admin ID: " + root.user-detail.admin_id;
                }

                Text {
                    text: "Username: " + root.user-detail.username;
                }

                Text {
                    text: "Role: " + root.user-detail.role;
                }

                Text {
                    text: "Error occurred during logout";
                    visible: root.error-logout;
                }

                HorizontalBox {
                    Button {
                        text: "Logout";
                        clicked => {
                            root.user-logout();
                        }
                    }

                    Button {
                        text: "Register";
                        clicked => {
                            root.user-register();
                        }
                    }
                }
            }
        }
    }
}
